### ISSUE TITLE
/sbin/ldconfig: /lib64/libcudnn.so.5 is not a symbolic link

### ISSUE THREAD

**Issue by dbrunmeir** [negativo17/cuda#1]
after installing the cuda packages (escpecially cuda-cudnn-* ) I get this following error message during dnf updates (I guess everytime ldd is called somewhere).

/sbin/ldconfig: /lib64/libcudnn.so.5 is not a symbolic link

any more infos needed? :-)

**Comment by scaronni** [comment]
Hello, problem with the packaging. Running `install` on a symlink copies the target. New build coming.

**Comment by roblem** [comment]
Just installed 2 days ago the nvidia and cuda driver/libraries in Fedora 24:
```
dnf -y install nvidia-driver nvidia-settings kernel-devel
dnf -y install cuda nvidia-driver-cuda cuda-devel cuda-samples
```
Navigating to the samples directory `/usr/share/cuda/samples/1_Utilities/deviceQuery` and attempting to make this to verify the installation gives:
```
deviceQuery.cpp:19:26: fatal error: cuda_runtime.h: No such file or directory
 #include <cuda_runtime.h>
                          ^
compilation terminated.
Makefile:250: recipe for target 'deviceQuery.o' failed
make: *** [deviceQuery.o] Error 1
```

Adding the cuda include folder to `INCLUDES` in `Makefile`:
```
INCLUDES  := -I../../common/inc,/usr/include/cuda
```
and running make, gives:
```
/usr/bin/crt/link.stub:2:26: fatal error: host_defines.h: No such file or directory
 #include "host_defines.h"
                          ^
compilation terminated.
Makefile:253: recipe for target 'deviceQuery' failed
make: *** [deviceQuery] Error 1
```

I have tried setting LD_LIBRARY_PATH to include `/usr/include/cuda` and continue to get the above error.
