### ISSUE TITLE
cmake find_package(CUDA) fails to set CUDA_INCLUDE_DIRS

### ISSUE THREAD

**Issue by akostadinov** [negativo17/cuda#11]
Hi, I tried to build an app that uses `cmake` on fedora 27. Presently cmake 3.10.1.
It failed with:

> -- Could NOT find CUDA (missing: CUDA_INCLUDE_DIRS) (found suitable version "9.1", minimum required is "7.5")

I have already `dnf install cuda-devel cuda-extra-libs`. Long story short, I had to hardcode `CUDA_INCLUDE_DIRS` to `/usr/include/cuda/` inside `/usr/share/cmake/Modules/FindCUDA.cmake` and the app built properly.

I have totally no idea though how this can be handled. I think this issue is related to #7 but here we talk about existing apps using `cmake` that we have no control over. I couldn't find any way to workaround the issue by setting env variables or something. The only way possible was to edit `/usr/share/cmake/Modules/FindCUDA.cmake`.

**Comment by scaronni** [comment]
Hello, `CUDA_INCLUDE_DIRS` is already in the environment file in `/etc/profile.d/cuda.sh`:

```
$ cat /etc/profile.d/cuda.sh 
if [ -x /usr/bin/cuda-g++ ]; then
  export HOST_COMPILER=/usr/bin/cuda-g++
fi

if [ -x /usr/libexec/cuda/open64/bin/nvopencc ]; then
  export PATH=$PATH:/usr/libexec/cuda/open64/bin
fi

if [ -d /usr/include/cuda ]; then
  export CUDA_INCLUDE_DIRS=/usr/include/cuda
fi
```

```
$ env | grep CUDA
CUDA_INCLUDE_DIRS=/usr/include/cuda
```

**Comment by scaronni** [comment]
So you should be good to go. Did you logout/reboot after installing the CUDA packages to get the correct environment?

**Comment by akostadinov** [comment]
I did reboot. This is an internal cmake variable. Setting an environment variable doesn't help. You can reproduce very easily.

1. create a CMakeLists.txt in some directory with content:
```
project(test-find-cuda)
find_package(CUDA 7.5 REQUIRED)
```
2. execute `CUDA_INCLUDE_DIRS="/usr/include/cuda/" cmake .`
```
-- The C compiler identification is GNU 7.3.1
-- The CXX compiler identification is GNU 7.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find CUDA (missing: CUDA_INCLUDE_DIRS) (found suitable version
  "9.1", minimum required is "7.5")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindCUDA.cmake:1082 (find_package_handle_standard_args)
  CMakeLists.txt:6 (find_package)


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.10)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/home/fedora/test_cuda/CMakeFiles/CMakeOutput.log".
See also "/home/fedora/test_cuda/CMakeFiles/CMakeError.log".
```

**Comment by akostadinov** [comment]
What we need is a fix in `/usr/share/cmake/Modules/FindCUDA.cmake`. And I hope that can be patched in fedora (because no other distro is using the `include/cuda` dir). This can be done in a better way than I initially did. On line 766 `PATH_SUFFIXES include` should be changed to `PATH_SUFFIXES include include/cuda`.

Another thing is that with cmake 3.11 I read that file will be deprecated and cuda support would be built in. It is important that this packaging works well with 3.11 as well.

**Comment by rokm** [comment]
Just hit this issue when trying to build custom version of OpenCV on Fedora 28. Then it turned out that CUDA cannot be found by CMake on my old Fedora 27 anymore, either...

The issue, as far as I can tell, is the removal of ```CUDA_INC_PATH``` environment variable from ```cuda.sh``` profile in cd2bda142241dfeaf0619681cfeb701d4f305d49. It was subsequently re-added as ```CUDA_INCLUDE_DIRS``` in e95b7006a44c987854fc683bdccb7940a5c428e6, but ```FindCUDA.cmake``` script is actually only trying to use ```CUDA_INC_PATH``` (or ```CUDA_PATH```) environment variable.

**Comment by scaronni** [comment]
Nice catch, I will make a test and re-add it. Thanks.

**Comment by scaronni** [comment]
Building it, sorry for the delay:

https://github.com/negativo17/cuda/commit/826952b4f00b3f9145dd81a46abde46fad2f356c

@rokm If you think there is anything else needed please let me know!

**Comment by satyajithj** [comment]
Faced a similar issue again.
Restart solves the problem.
