### ISSUE TITLE
CUDA 9.2 Version Update

### ISSUE THREAD

**Issue by mjmg** [negativo17/cuda#12]
CUDA 9.2 has been released for several months now with the latest patch just this August 2018. Any timetable on when can we expect the version to be bumped to 9.2?

Your last comment on this issue was:
https://negativo17.org/nvidia-driver/comment-page-8/#comment-53919

**Comment by scaronni** [comment]
About to roll out, including updated CUDNN and GCC compiler based on 7.3 for Fedora 28+.

**Comment by mjmg** [comment]
Thanks for this, will wait for the official release.
