### ISSUE TITLE
CUDA 10.1 Version Update

### ISSUE THREAD

**Issue by andyneff** [negativo17/cuda#16]
CUDA 10.1 has been released. Any timetable on when can we expect the version to be bumped to 10.1?

- [CUDA 10.1 looks like](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cuda-compiler-new-features) it has official GCC 8 support, so it looks like there will be no more need to bundle gcc 7 anymore.

**Comment by scaronni** [comment]
Still working on it. Base CUDA package is done, now it requires ``cuda-gcc`` 8 for Fedora 30, ``cuda-cudnn`` and rebuilds of other things that use CUDA libraries (``ffmpeg``, ``gstreamer1-plugins-bad``, ``ccminer`` etc.) before I can push it to the repositories.

Will be online in a few days.

**Comment by scaronni** [comment]
``cuda-gcc`` is built: https://github.com/negativo17/cuda-gcc/commit/ccf4ee47c829bffba41615d6828347d10f087208

Rebuilding the rest now.
