### ISSUE TITLE
No library found under: /usr/lib64/stubs/libcuda.so

### ISSUE THREAD

**Issue by skeydan** [negativo17/cuda#18]
Hi @scaronni thanks so much for your awesome work.
I switched to using your packages after the manual way didn't work for me any more with kernel 5.1, and the guys on AskFedora highly recommended negativo17 :-)

All worked fine for me but I have an error compiling tensorflow (in the manual way, it was pretty easy specifying the correct paths because all was beneath `usr/local/cuda`).

During configure, it says

```
Found CUDA 10.1 in:
    /usr/lib64
    /usr/include/cuda
Found cuDNN 7 in:
    /usr/lib64
    /usr/include/cuda
```

but during the build it looks for a `stub` library and can't find it:

```
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
	File "/home/key/code/tensorflow/third_party/gpus/cuda_configure.bzl", line 1266
		_create_local_cuda_repository(repository_ctx)
	File "/home/key/code/tensorflow/third_party/gpus/cuda_configure.bzl", line 1033, in _create_local_cuda_repository
		_find_libs(repository_ctx, cuda_config)
	File "/home/key/code/tensorflow/third_party/gpus/cuda_configure.bzl", line 608, in _find_libs
		_find_cuda_lib("cuda", repository_ctx, cpu_value, (cu...), ...)
	File "/home/key/code/tensorflow/third_party/gpus/cuda_configure.bzl", line 589, in _find_cuda_lib
		find_lib(repository_ctx, [("%s/%s" % (based...))], ...)))
	File "/home/key/code/tensorflow/third_party/gpus/cuda_configure.bzl", line 566, in find_lib
		auto_configure_fail(("No library found under: " + ",...)))
	File "/home/key/code/tensorflow/third_party/gpus/cuda_configure.bzl", line 325, in auto_configure_fail
		fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: No library found under: /usr/lib64/stubs/libcuda.so

```
Would you have an idea what could be the reason?

Many thanks!!

**Comment by scaronni** [comment]
Hello,

there are no stubs included in the packages, just the real libraries, like normal packages. Where it's checking for the library, make sure it's searching without the `stubs` path, for example: `/usr/lib64/libcuda.so`

That file in particular is in the drivers main package, `nvidia-driver-devel`.

**Comment by skeydan** [comment]
Thank you! I will create an issue in TensorFlow then, to see if there's a way to modify the `bazel` configuration.

**Comment by Jiangjiangzhang6** [comment]
Last login: Thu Mar 17 08:13:47 2022 from 120.240.53.20
bash: expor: command not found...
bash: rt: command not found...
Similar command is: 'tr'
File /public/home/zmsong/jjzhang/software/lib64/stubs/libcuda.so doesn't exist



its my problems withnot the root authority, how to slove this error ?
