### ISSUE TITLE
Bad soname for cudart

### ISSUE THREAD

**Issue by gcampax** [negativo17/cuda#21]
Since the update to `10.1.168-1.fc30`, the cuda-cudart includes `libcublas.so.10` -> `libcublas.so.10.2.0.168` (note the 2 at the end), while other libraries have sonames of the form `libcudart.so.10.1 -> libcudart.so.10.1.168` or `libcufft.so.10 -> libcufft.so.10.1.168`.
This change breaks tensorflow, which expects all libraries to have sonames with the same number.

Was it intentional? Is it possible to revert it and ensure that all libraries have consistent sonames, so should tensorflow be fixed?

**Comment by scaronni** [comment]
Hi, unfortunately this is how Nvidia distribute patches. To also keep the versions aligned it would mean providing the original libraries + the patched libraries in the same package, which does not make much sense.

Anyway I'm updating to CUDA 10.1 update 2 which is all versioned at 10.1.243.
