### ISSUE TITLE
Upgrade to cuda 11

### ISSUE THREAD

**Issue by drahnr** [negativo17/cuda#24]
Currently the repository contains cuda version `10.0`, but it would be great to have `11.0`.

Are there any plans to update the `cuda*` packages to the latest version for `fedora 32`?

Ref https://github.com/negativo17/compat-nvidia-repo/issues/1
Ref https://github.com/spearow/juice/issues/114
Ref https://github.com/spearow/juice/issues/115

**Comment by scaronni** [comment]
Yes I will, hopefully soon. I've been asked to help with the Blender build in Fedora, will do just after as I'm building Blender with CUDA support as part of the CUDA packages.

**Comment by drahnr** [comment]
Do you think you will find time for this soon~ish? Much appreciated!

**Comment by scaronni** [comment]
Sorry, moved house and got a few weeks without internet. Catching up now.

**Comment by scaronni** [comment]
As you can see it's not a small change: https://github.com/negativo17/cuda/commit/239c733956050015825c84ac2a30e8bfb5f95275

I will rewrite this commit as I make progress.

**Comment by drahnr** [comment]
I am happy to test this early on once you have test packages to grab :)

**Comment by scaronni** [comment]
Pushing the updated 11.1.1 now. The Java applications Nsight Compute and Nsight Systems are no longer part of the base CUDA package, they will be packaged separately (not sure though).

There is conflicting reports in the documentation, here it says GCC 10 is supported:

![image](https://user-images.githubusercontent.com/1983966/99502100-e9323f80-297c-11eb-9dc7-1aff96d9c4e0.png)

And here is not:

![image](https://user-images.githubusercontent.com/1983966/99502242-154dc080-297d-11eb-950b-2df57f96e51a.png)

Can you confirm that GCC 10 works with `nvcc` from CUDA 11.1.1? I haven't built the `cuda-gcc` package yet for Fedora 33.

**Comment by drahnr** [comment]
I will be able to test this towards the weekend. Thanks for all the work you put into this! :bow:

**Comment by scaronni** [comment]
> I will be able to test this towards the weekend. Thanks for all the work you put into this!

Any feedback? Does it work properly with GCC 10?

**Comment by drahnr** [comment]
I tested with the quicksort sample on a pascal gpu, it compiles fine and runs fine.

```
$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/10/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++,ada,go,d,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.1 20201016 (Red Hat 10.2.1-6) (GCC) 
```

```
../../bin/x86_64/linux/release/cdpSimpleQuicksort
GPU Device 0: "Pascal" with compute capability 6.1

Initializing data:
Running quicksort on 128 elements
Launching kernel on the GPU
Validating results: OK
```

The samples currently come with makefiles that expect `nvcc` in a different path, so you might want to adjust that, to just use the one from `$PATH` and strip all the dependencies on the `compat-gcc`.

Sorry for the long delay.

@scaronni ^^^^

**Comment by scaronni** [comment]
Dependency on `cuda-gcc` has been removed.
