### ISSUE TITLE
Can't find opencl libraries

### ISSUE THREAD

**Issue by pgera** [negativo17/cuda#3]
I've installed the drivers and the cuda packages from the repo, but I can't find open cl libraries. My system doesn't have libOpenCL.so. On a different system with cuda installed from some other repo (possibly nvidia's), I can see /usr/local/cuda-6.5/lib64/libOpenCL.so
/usr/local/cuda-6.5/lib64/libOpenCL.so.1

Edit: This is on RHEL7 btw
Edit2: I see this in your spec file:
Libraries in the driver package
rm -f %{buildroot}%{_libdir}/libOpenCL.so*

**Comment by scaronni** [comment]
`libOpenCL` is part of the ocl-icd package which in turn is part of the base Fedora and EPEL repositories. In both cases the drivers hard requires the dependency, so you can't install the drivers without OpenCL unless you're forcing the installation of the packages:

```
$ rpm -q --requires nvidia-driver-cuda.x86_64 | grep cl
ocl-icd
opencl-filesystem
$ rpm -ql ocl-icd.x86_64 | grep OpenCL
/usr/lib64/libOpenCL.so.1
/usr/lib64/libOpenCL.so.1.0.0
```
Maybe you did not install the CUDA part of the driver?
Just plainly install the packages and you should be good to go:

`yum install nvidia-driver-cuda nvidia-driver`

**Comment by pgera** [comment]
I have ocl-id, but it only installs libOpenCL.so.1 and libOpenCL.so.1.0.0. Am I supposed to create a symlink manually ?  I am able to run cuda programs. So the driver side of things is fine. I also see nvidia's icd file. Creating symlinks manually seems strange though.

Edit: Turns out that I had to install ocl-icd-devel to get that symlink. Maybe it should be in the requires ?

**Comment by scaronni** [comment]
Hi, `ocl-icd-devel` it's just needed if you need to build against it.
For runtime `ocl-icd` should be enough.
Which program are you trying to run that requires the unversioned `libOpenCL.so` library at runtime? That should only be used when linking to it.

**Comment by pgera** [comment]
I was trying to build OpenCL code. So maybe you are right about build v/s run. It's a bit confusing because "yum provides libOpenCL.so" doesn't return any results.

**Comment by scaronni** [comment]
What is stored in the metadata is the full path. You should try this:

`yum provides \*libOpenCL.so\*`
