### ISSUE TITLE
cuBLAS compilation failure: nv/target: No such file or directory

### ISSUE THREAD

**Issue by pjuhasz** [negativo17/cuda#31]
Hi, I'm experimenting with CUDA, and I get a compilation error when trying to compile any program that uses cuBLAS. I've first noticed the problem with whisper.cpp, but the simpleCUBLAS example program from Nvidia's official cuda-samples also fails with the same error.

```In file included from /usr/include/cublas_api.h:77,
                 from /usr/include/cublas_v2.h:69,
                 from simpleCUBLAS.cpp:40:
/usr/include/cuda_fp16.h:4086:10: fatal error: nv/target: No such file or directory
 4086 | #include <nv/target>
      |          ^~~~~~~~~~~
```
I installed the cuda-devel package version 12.3.101 and everything related from the fedora-nvidia repo, together with the nvidia-driver. I'm on an up-to-date Fedora 38 system.

```+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.29.06              Driver Version: 545.29.06    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Quadro M2000M                  Off | 00000000:01:00.0  On |                  N/A |
| N/A   43C    P8              N/A / 200W |     74MiB /  4096MiB |     19%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```

I'm not sure that this is a problem with your packages or Nvidia's upstream sources.

**Comment by pjuhasz** [comment]
It turns out that I didn't have the cuda-cccl-devel package installed. Having remedied that, I can now compile cuda-samples, but whisper.cpp still fails with a barrage of errors like `error: namespace "std" has no member "atomic_flag"`. I suppose these errors come from the fact that whisper.cpp (like most CUDA code out there) expects to find includes and libraries under /usr/local/cuda, while the Negativo17 packages install them elsewhere. But I don't really know how to fix the problem (other than installing the cuda toolkit from the official Nvidia source, which I wanted to avoid).

**Comment by scaronni** [comment]
Sorry, was away for holidays. The main difference between the upstream CUDA packages and these is that the headers are in `/usr/include/cuda` instead of `include` but relative to the CUDA root.

**Comment by zeroepoch** [comment]
@scaronni, I think something maybe happened to the cuda package spec between now (12.3.x) and when the following changelog entry was made (last line being the important one)?

```
* Tue Jul 20 2021 Simone Caronni <negativo17@gmail.com> - 1:11.4.0-1
- Update to 11.4.0.
- Update package names used in conflict statements to match upstream changes.
- Add missing CCCL (C++ Core Compute libraries )headers to devel subpackage.
```

Installing `cuda-cccl-devel` as @pjuhasz mentioned allowed me to compile gpu_burn. I feel there is a missing dependency here. `/usr/include/cuda_fp16.h` includes `nv/target`, where the former is provided by `cuda-cudart-devel`. Maybe `cuda-cccl-devel` could be considered a core requirement for `cuda-devel`?

**Comment by scaronni** [comment]
Coming with the CUDA 12.4 update packages, sorry for the delay. Thanks.
