### ISSUE TITLE
CMake can't find the CUDA libraries/headers

### ISSUE THREAD

**Issue by valadaptive** [negativo17/cuda#32]
CMake seems to have made some changes to how they search for the CUDA Toolkit (see [CMakeCUDAFindToolkit.cmake](https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/Internal/CMakeCUDAFindToolkit.cmake?ref_type=heads) for details).

This doesn't seem to work with the way CUDA libs are laid out when installed from this repo. Trying to `enable_language(CUDA)` in any `CMakeLists.txt` gives:

```
CMake Error at /home/va_erie/.local/lib/python3.12/site-packages/cmake/data/share/cmake-3.28/Modules/Internal/CMakeCUDAFindToolkit.cmake:148 (message):
  Couldn't find CUDA library root.
Call Stack (most recent call first):
  /home/va_erie/.local/lib/python3.12/site-packages/cmake/data/share/cmake-3.28/Modules/CMakeDetermineCUDACompiler.cmake:89 (cmake_cuda_find_toolkit)
  CMakeLists.txt:296 (enable_language)
```

I ran into this with llama.cpp, and [at least one other person ran into this on another project that uses cuBLAS](https://github.com/ggerganov/whisper.cpp/issues/1684), and their only solution was to uninstall everything from this repo and use the official NVIDIA one insetad.

**Comment by scaronni** [comment]
Compared to the official packages, the main difference is that the headers are not in `<CUDA_ROOT>/include` but in `/usr/include/cuda`. After adding that to the search path you should be good to go.

Example: https://github.com/negativo17/ffmpeg/blob/master/ffmpeg.spec#L528

**Comment by valadaptive** [comment]
Going off memory now since I reinstalled everything from the NVIDIA repo.

The problem I ran into was [finding the CUDA library root](https://gitlab.kitware.com/cmake/cmake/-/blob/9090d340b45fa5092443d1abcf959a9a35a4d0e7/Modules/Internal/CMakeCUDAFindToolkit.cmake#L139-149). CMake *seems* to have found the headers just fine IIRC, but it expects all the CUDA libs to be in one folder. Its last resort is `/usr/lib/cuda`, which didn't seem to exist when installing CUDA from this repo.

**Comment by stevestorey** [comment]
If this is a hijack, then apologies and I'll raise a separate issue, but I _think_ it's related - I'm also trying to build llama.cpp with cuBLAS enabled, I can get the headers resolved, but then I ran into the same problem reported in the issue linked in the original issue post - https://github.com/ggerganov/whisper.cpp/issues/1684 - 
```
/usr/include/cuda/std/detail/libcxx/include/__cuda/atomic_prelude.h(29): error: identifier "ATOMIC_LLONG_LOCK_FREE" is undefined
      static_assert(ATOMIC_LLONG_LOCK_FREE == 2, "");
                    ^

/usr/include/cuda/std/detail/libcxx/include/__cuda/atomic_prelude.h(30): error: identifier "ATOMIC_POINTER_LOCK_FREE" is undefined
      static_assert(ATOMIC_POINTER_LOCK_FREE == 2, "");
                    ^

ggml-cuda.cu(6519): error: namespace "std" has no member "atomic_flag"
      std::atomic_flag& lock;
           ^

ggml-cuda.cu(6520): error: namespace "std" has no member "atomic_flag"
      scoped_spin_lock(std::atomic_flag& lock) : lock(lock) {
```
along with a bunch of other similar missing defines. I'm not a  C++ developer, but from my googling, it seems that the cuda libraries want to assert that the atomics support is all lock free, but clearly _something_ isn't right. The original poster on the linked issue says that upon switching to the standard installer, the problem went away which would at least _suggest_ it's a packaging issue ?

To get this far, I mofieid the llama.cpp `Makefile` to add `-I/usr/include/cuda` so it would find the headers. Same result from using clang or gcc - `make -j LLAMA_CUBLAS=1  NVCC_PREPEND_FLAGS='-allow-unsupported-compiler'` (the last bit because I'm on F39 - but same result using clang 16 on F38 which is a supported environment). Any ideas how to solve it ?

**Comment by scaronni** [comment]
Which OS are you using? Fedora 39? There is a limit of GCC supported by CUDA, that's why there's an additional compiler in the repositories of Fedora 38 and 39:
```
fedora-39/x86_64/cuda-gcc-12.3.0-1.fc39.x86_64.rpm
fedora-39/x86_64/cuda-gcc-c++-12.3.0-1.fc39.x86_64.rpm
fedora-39/x86_64/cuda-gcc-gfortran-12.3.0-1.fc39.x86_64.rpm
```
If you install it, you get all these binaries:
```
$ find /usr/bin/cuda/
/usr/bin/cuda/
/usr/bin/cuda/gcc
/usr/bin/cuda/gcc-ar
/usr/bin/cuda/gcc-nm
/usr/bin/cuda/gcc-ranlib
/usr/bin/cuda/gcov
/usr/bin/cuda/gcov-dump
/usr/bin/cuda/gcov-tool
/usr/bin/cuda/lto-dump
/usr/bin/cuda/c++
/usr/bin/cuda/cpp
/usr/bin/cuda/g++
```
Along with an NVCC flag to automatically use it:

```
$ cat /etc/profile.d/cuda-gcc.sh 
export NVCC_PREPEND_FLAGS='-ccbin /usr/bin/cuda'
```

**Comment by steve-birdie** [comment]
Thanks for the reply

> Which OS are you using? Fedora 39? 

Yes

> There is a limit of GCC supported by CUDA, that's why there's an additional compiler in the repositories of Fedora 38 and 39:

Right - yes, they were in fact installed when I did `dnf install cuda-nvcc`, but I failed to properly logout and in again it would seem in order to pick up the new profile vars. Having done so, I no longer need the `-allow-unsupported-compiler` flag, (so now run ` make -j LLAMA_CUBLAS=1`) but I still have the problem with the errors about atomics :(. 

**EDIT:** I'm a bit more confused now - it turns out that I don't even need to put `-I/usr/include/cuda` into the Makefile any more - nvcc is somehow finding that on its own (is that a feature of your packaging?) - so I can now repro the errors with:
```
$ nvcc  ggml-cuda.cu -o ggml-cuda.o
/usr/include/cuda/std/detail/libcxx/include/__cuda/atomic_prelude.h(21): error: identifier "ATOMIC_BOOL_LOCK_FREE" is undefined
     static_assert(ATOMIC_BOOL_LOCK_FREE == 2, "");
.
.
```

**EDIT 2:** Have now got to the direct cause - which is indeed the packaging of cuda-nvcc applying a /usr/bin/nvcc.profile file - commenting out `INCLUDES += "-I/usr/include/cuda"` is enough to make the compilation work. I still don't need to edit the `Makefile` to explicitly re-add the include files again, so they must still be included somehow (maybe via `CUDA_INCLUDE_DIRS`?)

**Comment by adro79** [comment]
Hi, I'm having the same problem building [OpenMoonray](https://github.com/dreamworksanimation/openmoonray) with CUDA support:

```
CMake Error at /usr/share/cmake/Modules/Internal/CMakeCUDAFindToolkit.cmake:148 (message):
  Couldn't find CUDA library root.
Call Stack (most recent call first):
  /usr/share/cmake/Modules/CMakeDetermineCUDACompiler.cmake:89 (cmake_cuda_find_toolkit)
  CMakeLists.txt:20 (enable_language)
```

I'm using Fedora 40. Have you found a solution to this? Thanks.

**Comment by lexasub** [comment]
> Which OS are you using? Fedora 39? There is a limit of GCC supported by CUDA, that's why there's an additional compiler in the repositories of Fedora 38 and 39:
> 
> ```
> fedora-39/x86_64/cuda-gcc-12.3.0-1.fc39.x86_64.rpm
> fedora-39/x86_64/cuda-gcc-c++-12.3.0-1.fc39.x86_64.rpm
> fedora-39/x86_64/cuda-gcc-gfortran-12.3.0-1.fc39.x86_64.rpm
> ```
> 
> If you install it, you get all these binaries:
> 
> ```
> $ find /usr/bin/cuda/
> /usr/bin/cuda/
> /usr/bin/cuda/gcc
> /usr/bin/cuda/gcc-ar
> /usr/bin/cuda/gcc-nm
> /usr/bin/cuda/gcc-ranlib
> /usr/bin/cuda/gcov
> /usr/bin/cuda/gcov-dump
> /usr/bin/cuda/gcov-tool
> /usr/bin/cuda/lto-dump
> /usr/bin/cuda/c++
> /usr/bin/cuda/cpp
> /usr/bin/cuda/g++
> ```
> 
> Along with an NVCC flag to automatically use it:
> 
> ```
> $ cat /etc/profile.d/cuda-gcc.sh 
> export NVCC_PREPEND_FLAGS='-ccbin /usr/bin/cuda'
> ```

hello, where is packages? (my os is fedora 41-rawhide) on this link https://developer.download.nvidia.com/compute/cuda/repos/fedora39/x86_64/ doesn't exist

**Comment by scaronni** [comment]
> hello, where is packages? (my os is fedora 41-rawhide) on this link https://developer.download.nvidia.com/compute/cuda/repos/fedora39/x86_64/ doesn't exist

That package is not in the NVIDIA CUDA repository, it's in my repository or here: https://copr.fedorainfracloud.org/coprs/slaanesh/cuda-gcc/

**Comment by valadaptive** [comment]
I ran into this again trying to build a CMake-based project that uses CUDA. Why was this closed? I'm not sure I was given an actionable solution.

I'm not sure what you mean by:

> Compared to the official packages, the main difference is that the headers are not in <CUDA_ROOT>/include but in /usr/include/cuda. After adding that to the search path you should be good to go.

This isn't about finding the headers. The [CMakeCUDAFindToolkit.cmake](https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/Internal/CMakeCUDAFindToolkit.cmake) helper, which is built into CMake, is looking for the CUDA library root but cannot find it. AFAIK, it doesn't even look at the include paths, and at this point, we haven't even started compiling.

I cannot find anything to pass to CMake that lets it work with the directory layout defined here. I believe this is due to CMake's helper script *claiming* to support "scattered" installations of CUDA, but [assuming that the `[library root]/nvvm/libdevice` directory will always exist](https://gitlab.kitware.com/cmake/cmake/-/blob/e2ebb41b626ea39d166fbc2c0ba750893d60ea01/Modules/Internal/CMakeCUDAFindToolkit.cmake#L138-150).

Is there something that can be done to fix this *here*, or is CMake just wrong?

**Comment by scaronni** [comment]
> I cannot find anything to pass to CMake that lets it work with the directory layout defined here. I believe this is due to CMake's helper script _claiming_ to support "scattered" installations of CUDA, but [assuming that the `[library root]/nvvm/libdevice` directory will always exist](https://gitlab.kitware.com/cmake/cmake/-/blob/e2ebb41b626ea39d166fbc2c0ba750893d60ea01/Modules/Internal/CMakeCUDAFindToolkit.cmake#L138-150).

I don't have this issue, around October I've added a couple of changes explicitly to accomodate this use case:

- https://github.com/negativo17/libnvvm/commit/ed2ebb738338fdf6fcab9ed059348baa3e3a5e3f
- https://github.com/negativo17/cuda/commit/32fc246a874601a05dfa3dddf290fb34ee70c9ec

Where the main point is actually this: https://github.com/negativo17/libnvvm/blob/master/libnvvm.spec#L50-L51

Do you have some more specific information?

**Comment by valadaptive** [comment]
> > I cannot find anything to pass to CMake that lets it work with the directory layout defined here. I believe this is due to CMake's helper script _claiming_ to support "scattered" installations of CUDA, but [assuming that the `[library root]/nvvm/libdevice` directory will always exist](https://gitlab.kitware.com/cmake/cmake/-/blob/e2ebb41b626ea39d166fbc2c0ba750893d60ea01/Modules/Internal/CMakeCUDAFindToolkit.cmake#L138-150).
> 
> I don't have this issue, around October I've added a couple of changes explicitly to accomodate this use case:
> 
>     * [negativo17/libnvvm@ed2ebb7](https://github.com/negativo17/libnvvm/commit/ed2ebb738338fdf6fcab9ed059348baa3e3a5e3f)
> 
>     * [32fc246](https://github.com/negativo17/cuda/commit/32fc246a874601a05dfa3dddf290fb34ee70c9ec)
> 
> 
> Where the main point is actually this: https://github.com/negativo17/libnvvm/blob/master/libnvvm.spec#L50-L51
> 
> Do you have some more specific information?

Apparently I hadn't updated my system in a while. I'd tried updating the CUDA packages, but maybe I had to update to Fedora 43? Either way, it works now.

**Comment by scaronni** [comment]
I pushed the same updates to `el8`, `el9`, `el10`, `fc42` and `fc43` so staying on Fedora 42 and just update was probably fine. Thanks.
