### ISSUE TITLE
wrong path for includedir in pkgconfig

### ISSUE THREAD

**Issue by antonheryanto** [negativo17/cuda#4]
seem pkgconfig includedir path reverted back from /usr/include to /usr/include/cuda in b7f9f77 which causing cuda header cannot be find. in happen to me in cuda package version 8.0.61-5 on fedora 26

**Comment by scaronni** [comment]
...which is correct, as the CUDA headers are all in `/usr/include/cuda` since more than a year:

```
$ rpm -qal cuda-*devel | grep /usr/include/cuda/ | wc -l
1159
```

**Comment by antonheryanto** [comment]
Thanks for the project and quick response. 

Headers are correctly reside in /usr/include/cuda, but the includedir path is incorrect in pkgconfig file for example /usr/lib64/pkgconfig/cuda.pc (and others cuda-devel pkgconfig file) 
``` 
libdir=/usr/lib64
includedir=/usr/include

Name: cuda
Description: CUDA Driver Library
Version: 8.0.61
Libs: -L${libdir} -lcuda
Cflags: -I${includedir} 
```
sorry if my issue is not clear

**Comment by scaronni** [comment]
Argh. Nothing that I've used so far uses pkgconfig for the Nvidia libraries.
Thanks for reporting, new build coming.
