### ISSUE TITLE
cuda-samples cannot be installed due to non existing package

### ISSUE THREAD

**Issue by isloven** [negativo17/cuda#6]
It looks like the cuda-samples package on Fedora 27 depends on non-existing compat-gcc-64-c++ package.

$ sudo dnf install cuda-samples
Error: 
 Problem: conflicting requests
  - nothing provides compat-gcc-53-c++ needed by cuda-samples-1:9.0.176-1.fc27.x86_64
  - nothing provides compat-gcc-64-c++ needed by cuda-samples-1:9.0.176-2.fc27.x86_64
  - nothing provides compat-gcc-64-c++ needed by cuda-samples-1:9.1.85-1.fc27.x86_64

I assume the cuda.spec file needs to be updated to depend on cuda-gcc-c++ package instead?

```
diff --git a/cuda.spec b/cuda.spec
index f91487f..9473e20 100644
--- a/cuda.spec
+++ b/cuda.spec
@@ -388,7 +388,7 @@ Obsoletes:      %{name}-samples < %{?epoch:%{epoch}:}%{version}
 Provides:       %{name}-samples = %{?epoch:%{epoch}:}%{version}
 Requires:       cuda-devel = %{?epoch:%{epoch}:}%{version}
 %if 0%{?fedora}
-Requires:       compat-gcc-64-c++
+Requires:       cuda-gcc-c++
 %else
 Requires:       gcc
 %endif
```

**Comment by scaronni** [comment]
Thanks for reporting. New build coming soon.

**Comment by isloven** [comment]
Confirmed working with latest update. 

Thanks!

**Comment by CdAB63** [comment]
Seems it's happening again:

[CdAB63@localhost xorg]$ sudo dnf install cuda-samples
Última verificação de data de vencimento de metadados: 2:26:39 atrás em sáb 05 mai 2018 10:08:49 -03.
Erro: 
 Problema: conflicting requests
  - nothing provides cuda-gcc-c++ needed by cuda-samples-1:9.1.85.3-5.fc28.x86_64
[CdAB63@localhost xorg]$

**Comment by scaronni** [comment]
The Fedora 28 repository is missing cuda-gcc. I haven't built yet a working GCC 6.4 compiled with GCC 8. So cuda-gcc, ccminer and blender are missing. I'm still working on it.

Patches welcome: https://github.com/negativo17/cuda-gcc

**Comment by scaronni** [comment]
Build coming.

**Comment by RMPR** [comment]
Sorry for necroposting, 
```
Error: 
 Problem: conflicting requests
  - nothing provides cuda-gcc-c++ needed by cuda-samples-1:10.1.243-1.fc31.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```
Seems like there's no build for fedora 31 yet, how can I build it myself ?

**Comment by scaronni** [comment]
Fixed now, sorry.
